### ISSUE TITLE
Settings options not being saved on Windows

### ISSUE THREAD

**Issue by webmandesign** [absalomedia/vagrant-manager#15]
## Describe the bug

Settings options are not being saved. Every time I start the app I need to set the options again. I'm using Windows 10 OS.

## To Reproduce

1. Start the app.
2. Right-click the app icon in Windows 10 taskbar and select settings.
3. Change settings options and close the settings window.
4. Right-click the app icon in taskbar and quit the app.
5. Start the app again.
6. Right-click the app icon in taskbar and select settings to see they are reset to default state. None of our options tweaks have been saved.

## Expected behavior

Would be great if the settings options are saved permanently and applied when app is started next.

## Desktop

 - OS: Windows 10
 - Version 2.2.0

**Comment by absalomedia** [comment]
Been able to replicate this on Windows 10 environment

**Comment by absalomedia** [comment]
This should now be fixed with the 2.3.2 release

**Comment by webmandesign** [comment]
Hi,

Thank you for the fix! Indeed, the options stays saved in next Vagrant Manager start.

However, as I have the "Enable console" option saved now, I've done a vagrant up on my box, but no console was present after the procedure ended, unlike it was before. Anything changed in this matter?

I can also see there is a new "Automatically update box" option. Should I check also this option to see the console output? Or is this for something else?

Thanks!

**Comment by absalomedia** [comment]
@webmandesign the automatically update box option runs the box checking / updating sequence as part of Vagrant being sent the 'up' command. I'll investigate why the console isn't running
