### ISSUE TITLE
autoUpdater.setFeedURL is not a function

### ISSUE THREAD

**Issue by kmgalanakis** [absalomedia/vagrant-manager#9]
**Describe the bug**
Installed on Windows 10 and when run, I got an error saying

`autoUpdater.setFeedURL is not a function`

**To Reproduce**
1. Install on Windows 10 and try to run the app.

**Expected behavior**
The app should start without errors.

**Screenshots**
![error](https://user-images.githubusercontent.com/1268089/52934147-42131500-335e-11e9-89b8-afae6df2168b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 72.0.3626.109 (Official Build) (64-bit)

**Comment by absalomedia** [comment]
Fixed by 2.1.5 release

**Comment by kmgalanakis** [comment]
👍
